pipeline {
    agent any

    stages {
        stage('task3 - terraforming infrastructure'){
            steps {
              dir("/var/lib/jenkins/poc_terra1/task3")
              { 
              	echo 'Building environment'
	        sh 'PATH=$PATH:/usr/local/bin'
                sh 'pwd'
              	sh 'terraform task3/init'
	        sh 'terraform task3/plan -out my_plan'
                sh 'terraform task3/apply my_plan'
              }
            }
        }
    }
}
